calc_and_save_stats('../data/bwscafe1/bwscafe1_task_ordering_coffee_vertical_disparity.mat')
calc_and_save_stats('../data/bwsdrdp6/bwsdrdp6_task_walk_2_vertical_disparity.mat')
calc_and_save_stats('../data/bwsdrdp6/bwsdrdp6_task_walk_1_vertical_disparity.mat')
calc_and_save_stats('../data/bwsnat5/bwsnat5_task_nature_walk_1_vertical_disparity.mat')
calc_and_save_stats('../data/bwsnat5/bwsnat5_task_campus_walk_3_vertical_disparity.mat')
calc_and_save_stats('../data/bwsdrdp6/bwsdrdp6_task_walk_3_vertical_disparity.mat')
calc_and_save_stats('../data/bwssand1/bwssand1_task_sandwich_vertical_disparity.mat')
calc_and_save_stats('../data/bwsure1/bwsure1_task_nature_walk_2_vertical_disparity.mat')
calc_and_save_stats('../data/gesnat1/gesnat1_task_nature_walk_1_vertical_disparity.mat')
calc_and_save_stats('../data/gesnat1/gesnat1_task_campus_walk_3_vertical_disparity.mat')
calc_and_save_stats('../data/gescafe2/gescafe2_task_ordering_coffee_vertical_disparity.mat')
calc_and_save_stats('../data/gesdrdp1/gesdrdp1_task_walk_1_vertical_disparity.mat')
calc_and_save_stats('../data/gesdrdp1/gesdrdp1_task_walk_2_vertical_disparity.mat')
calc_and_save_stats('../data/gesdrdp1/gesdrdp1_task_walk_3_vertical_disparity.mat')
calc_and_save_stats('../data/gessand1/gessand1_task_sandwich_vertical_disparity.mat')
calc_and_save_stats('../data/gesure1/gesure1_task_nature_walk_2_vertical_disparity.mat')

calc_and_save_stats('../data/hmfnat1/hmfnat1_task_nature_walk_1_vertical_disparity.mat')
calc_and_save_stats('../data/hmfnat1/hmfnat1_task_campus_walk_3_vertical_disparity.mat')
calc_and_save_stats('../data/hmfure1/hmfure1_task_nature_walk_2_vertical_disparity.mat')
calc_and_save_stats('../data/hmfdrdp1/hmfdrdp1_task_walk_1_vertical_disparity.mat')
calc_and_save_stats('../data/hmfdrdp1/hmfdrdp1_task_walk_2_vertical_disparity.mat')
calc_and_save_stats('../data/hmfdrdp1/hmfdrdp1_task_walk_3_vertical_disparity.mat')
calc_and_save_stats('../data/hmfcafe1/hmfcafe1_task_ordering_coffee_vertical_disparity.mat')

